### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by louisvivier** [BaronMsk/transmission-telegram#1]
Hello, 

I would like to know if you are planning to release this docker image on the docker hub soon ?

Tx for your work !

**Comment by BaronMsk** [comment]
> Hello,
> 
> I would like to know if you are planning to release this docker image on the docker hub soon ?
> 
> Tx for your work !

Hi , For the service to work it is not necessary to place the image on the docker hub. Just run docker-compose up -d --build

**Comment by louisvivier** [comment]
I need to run it on Synology DSM, so I don’t have the CLI tool. At least I need a docker image that I can upload on the system manually.

**Comment by BaronMsk** [comment]
> I need to run it on Synology DSM, so I don’t have the CLI tool. At least I need a docker image that I can upload on the system manually.

ok, special for you: https://hub.docker.com/r/baronmsk/transmission-telegram/

**Comment by louisvivier** [comment]
Thank you very much !
